### ISSUE TITLE
quit command not working

### ISSUE THREAD

**Issue by JJBlue** [LukWebsForge/SourceLogger#1]
This is a great project. I searched for a solution to redirect the input/output of the game. And The output works great. But when I write "quit" nothing happens.
How can I stop the server?

**Comment by JJBlue** [comment]
I created a pull request

**Comment by lukbukkit** [comment]
As far as I can remember, I built this project to be used with the systemd, which hasn't a direct user input. But it's good idea to implement this feature, thanks a lot for your pull request! I will test it soon and take a second look at the code.
